Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 261, in <module>
    test_threshold(paramsid=30)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 251, in test_threshold
    optimizer.zero_grad()
NameError: name 'optimizer' is not defined
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

